<h1>Backup</h1>

<? if($backupLink !== FALSE) { ?>
<p>Your data has been backed up and is available for download at the following links:</p>

<ul>
<li>Database: <a href="<?= $backupLink[0] ?>"><?= $backupLink[0] ?></a></li>
<li>Submission PDFs: <a href="<?= $backupLink[1] ?>"><?= $backupLink[1] ?></a></li>
<li>Generated PDFs: <a href="<?= $backupLink[2] ?>"><?= $backupLink[2] ?></a></li>
</ul>
<? } ?>

<p>This tool will backup all of the data pertaining to your website (this excludes the oneapp installation base). Specifically, the database, any submission PDFs, and any generated PDFs (generated by admins to pdf/ directory) will be backed up.</p>

<p><b>Disabled on demo system to prevent flooding.</b></p>

<form method="post" action="backup.php">
<input type="submit" name="backup" value="Backup" />
</form>
